version: "3.7"

services:
  coffeeshop-service:
    build: 
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - mongo-db
    networks:
      - container-network

  mongo-db:
    image: "mongo:latest"
    ports:
      - 27017:27017
    networks:
      - container-network

networks:
  container-network:
    driver: bridge